[package]
name = "retro8"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
retro8-utils = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
